### ISSUE TITLE
Ability to select text in code?

### ISSUE THREAD

**Issue by craigomac** [ronjb/selectable#1]
Is there anything planned for making text selectable in code? I'm not sure how this would work—perhaps passing keys from the Text widgets to be selected?

**Comment by ronjb** [comment]
@craigomac Thanks for the feedback. I think I may have some time to implement these changes either this coming weekend, or the weekend after that. I'll let you know when the new version has been pushed.

**Comment by craigomac** [comment]
No worries! In the meantime I've using a regular text widget and setting background colours on spans in the counterpart text, instead of setting a selection in it (I don't know why it took me so long to think of that!). In any case, it will be a useful feature for `selectable`.

**Comment by ronjb** [comment]
Version 0.2.0 was just released, which has this feature. See the example app, which is included with the package to see how to programmatically select text. Let me know if you have any questions.

At some point I'll add information to the README about how to use this feature, but for now the example app and well documented source code are the best resource.
