### ISSUE TITLE
Ability to select all text given a default "Select All" option. 

### ISSUE THREAD

**Issue by Hamza3620** [ronjb/selectable#10]
Hi, this is a really helpful package that wraps around any number of text widgets and allows selection. 
In my case, a requirement is to select all text given a default "Select All" option. The number of text widgets inside changes dynamically so giving a random index to _selectWordsBetweenIndexes(start, end)_ ends up with different behavior. 

Would it be possible for you to provide a Select All option too?

Thanks!

**Comment by ronjb** [comment]
@Hamza3620,

I just released a new version of selectable (0.2.9) where the SelectableController class now has a `selectAll()` method. See the example app code for an example of how to use it.
