### ISSUE TITLE
Error: The non-abstract class 'SelectableFragment' is missing

### ISSUE THREAD

**Issue by SameerGhaffar** [ronjb/selectable#20]
/C:/Users/sameer/AppData/Local/Pub/Cache/hosted/pub.dev/float_column-2.1.1/lib/src/selectable_fragment.dart:19:7: Error: The non-abstract class 'SelectableFragment' is missing implementations for these members:
 - Selectable.boundingBoxes
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SelectableFragment
      ^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/rendering/selection.dart:147:18: Context: 'Selectable.boundingBoxes' is defined here.
  List<Rect> get boundingBoxes;
                 ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1549

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by ronjb** [comment]
Just published version 0.3.1 which depends on an updated float_column version that fixes the compile issue with Flutter 3.19.0.
