### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by DazzlingCVa** [ronjb/selectable#4]
How to use this function in Customscrollview.
if i use this function in Customscrollview i Got This Error
**36 pos 16: 'vp != null': is not true.**

**Comment by ronjb** [comment]
I’ll need reproducible steps and a stack trace if possible. No one else has reported that error, so without context it’s going to be pretty impossible to debug.

**Comment by ronjb** [comment]
@DazzlingCVa,

I did some testing to see if I could reproduce the problem you're seeing, and was unable to, until on a whim I tried placing the Selectable class outside of the scrollable widget. Then, when double tapping to select a word, I'm seeing the same error.

The Selectable widget needs to a descendent of the scrollable widget, and an ancestor of the text widget(s) you want to enable selection over. I'll update the docs to make this clear.

By the way, the latest version of the Selectable package's example app uses a CustomScrollView, so you can use that as an example: https://github.com/ronjb/selectable/blob/main/example/lib/main.dart

**Comment by ronjb** [comment]
@DazzlingCVa, were you able to get it working? Let me know if you have further questions.

**Comment by DazzlingCVa** [comment]
Again I Got Error in singlechildscrollview
anchor !=null
its not True

**Comment by ronjb** [comment]
Can you give a little more info? Some sample code that exhibits the problem, a stack trace of the exception, etc.?

And just checking, the Selectable widget is a child of the SingleChildScrollView, right?

Is your code is structured something like this?

```dart
Scaffold(
  body: SingleChildScrollView(
    child: Selectable(
      child: Column(
        children: [
          Text('... a lot of text ...'),
          // ... more widgets of any type that might contain text ...
        ],
      )
    )
  )
)
```

**Comment by DazzlingCVa** [comment]
yes

**Comment by ronjb** [comment]
Can you provide more information about when you see this error? For example, are you dragging a selection handle when it happens?

Can you provide an example of text that is being selected? Anything that would help me to be able to reproduce the bug so I can debug it. Thanks!

**Comment by DazzlingCVa** [comment]
Can you provide more information about when you see this error? For example, are you dragging a selection handle when it happens? 
Yes when i dragged a text I got this error

**Comment by ronjb** [comment]
@DazzlingCVa,

I recently fixed an issue related to dragging the selection handles (#7). Can you still reproduce the problem you were seeing?  If so, please provide more detailed information on how to reproduce the problem, ideally with some sample code that shows how you are using the Selectable library. Thanks!

**Comment by ronjb** [comment]
I'm going to close this for now, since I haven't heard back in a while. Feel free to re-open it with more details if you're still experiencing the problem.
