### ISSUE TITLE
How to make a Text inside Selectable, unselectable and how to not select the white space in between widgets

### ISSUE THREAD

**Issue by mohammadamircarv** [ronjb/selectable#9]
As you can see, this image is with the use of the `SelectionArea`, so the Text `JohnDoe` is not selected (because I used a `SelectionContainer.disabled` on top of it) and the space in between widgets is not selected as well:

![Screenshot_1666339628](https://user-images.githubusercontent.com/112618246/197145952-81069966-e28a-4289-a872-2a2675f4d9b0.png)

This is with the use of `Selectable`, and the white space and also the `JohnDoe` Text are selected:
![Screenshot_1666339799](https://user-images.githubusercontent.com/112618246/197146478-adadaab4-f824-41b9-9357-97065bf73ef6.png)

How can I get the same result as the `SelectionArea` with `Selectable`?

I appreciate your answer to this question.

**Comment by ronjb** [comment]
@mohammadamircarv,

Just released a new version of selectable (0.2.9) that provides a way to customize how the selection rectangles are computed, and by default now shows them as separate lines instead of merged together.

I think this addresses all of your questions, correct? If not, let me know.
